import { isNumber } from "sniffly";

/** Generates non-secure random id segment */
function _getSimpleIdSegment() {
    return Math.random().toString(36).slice(2)
}

/** Generates non-secure simple random ids */
function getSimpleRandomId(sectionCount?: number): string {

    sectionCount = isNumber(sectionCount, {positive: true}) 
        ? sectionCount
        : 1

    let id = 'ID' // we force the begining to guarantee it starts with a letter
    for (let i=0; i<sectionCount; i++) {
        id += '-' + _getSimpleIdSegment()
    }

    return id
}


let _ID = 0
/** Returns a unique id 
 * 
 * ⚙️ id generated by auto incrementing a global counter
*/
function getUniqueSeqId() {
    _ID ++
    const idString = _ID.toString(36)
    return 'SEQ-UID--' + idString
}

export { getSimpleRandomId, getUniqueSeqId}